site_name: DeepNet Wiki
site_url: https://macinsight.github.io
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple
markdown_extensions:
  - admonition
plugins:
  - search
